### ISSUE TITLE
Program dies on Mac (hardcoded Windows font location)

### ISSUE THREAD

**Issue by Zoom67** [hmtavares/sob_experiments#2]
[carey:~/dev/python/sob_experiments] master ± python hexgame.py
Traceback (most recent call last):
  File "hexgame.py", line 165, in <module>
    display  = map_display.MapDisplay()
  File "/Users/carey/dev/python/sob_experiments/map_display.py", line 143, in __init__
    self.font = pygame.font.Font('C:/WINDOWS/Fonts/arial.TTF', 14)
OSError: unable to read font file 'C:/WINDOWS/Fonts/arial.TTF'

**Comment by hmtavares** [comment]
Give branch mac-font a try and see if that fixes it

**Comment by Zoom67** [comment]
Yep! SHIP IT!!
